version: "3"
services:
    frontend:
        container_name: client
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: react
        ports:
            - "3001:3001"
        volumes:
            - ./client
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:5001/
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: server
        ports:
            - "5001:5001"
        volumes:
            - ./server
        environment:
            - MONGO_URL=mongodb://172.17.0.1:27017
        links:
            - mongo

    mongo:
        image: mongo
        container_name: mongo
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /mongodb/database:/data/db
        ports:
            - 27017:27017
        expose:
            - 27017
        restart: always
